Repository dm-vdo/vdo-devel, pull requests merged in 2024-05, with the labels that each got.

#140 Release version 8.3.0.70
  src/packaging/github/changelog
Labels: private testing done

#141 [VDO-5762] Fix nightly run of DMTest.
  src/Makefile
  src/perl/dmtest/DMTest.pm
  src/perl/dmtest/Makefile
Labels: private testing done

#123 [VDO-5724] Use lvm devices file directly
  src/perl/Permabit/BlockDevice.pm
  src/perl/Permabit/BlockDevice/ISCSI.pm
  src/perl/Permabit/BlockDevice/VDO.pm
  src/perl/Permabit/BlockDevice/VDO/Managed.pm
  src/perl/Permabit/BlockDevice/VDO/Unmanaged.pm
  src/perl/Permabit/VolumeGroup.pm
Labels: private testing done

#142 [VDO-5576] Shut down NFS server after stopping export.
  src/perl/Permabit/FileSystem.pm
Labels: private testing failed, private testing done

#144 dm vdo test: remove flushnop test device
  src/c++/devices/Makefile
  src/c++/devices/flushnop/Makefile
  src/c++/devices/flushnop/Makefile.common
  src/c++/devices/flushnop/Makefile.dkms
  src/c++/devices/flushnop/dkms.conf
  src/c++/devices/flushnop/dmFlush.c
  src/c++/devices/flushnop/limiter.c
  src/c++/devices/flushnop/limiter.h
  src/perl/Permabit/StorageStack.pm
  src/perl/vdotest/VDOTest/BlockDevice01.pm
Labels: private testing done

#145 Remove patchset generation tree
  src/packaging/patchset/MANIFEST.yaml
  src/packaging/patchset/Makefile
  src/packaging/patchset/cover.yaml
  src/packaging/patchset/dedupe1.yaml
  src/packaging/patchset/dedupe2.yaml
  src/packaging/patchset/doc.yaml
  src/packaging/patchset/murmur.yaml
  src/packaging/patchset/queue.yaml
  src/packaging/patchset/src/Kconfig
  src/packaging/patchset/src/Makefile
  src/packaging/patchset/src/build.txt
  src/packaging/patchset/src/dedupe1.txt
  src/packaging/patchset/src/dedupe2.txt
  src/packaging/patchset/src/doc.txt
  src/packaging/patchset/src/murmur.txt
  src/packaging/patchset/src/queue.txt
  src/packaging/patchset/src/target.txt
  src/packaging/patchset/src/threads.txt
  src/packaging/patchset/src/uds.txt
  src/packaging/patchset/src/vdo.txt
  src/packaging/patchset/target.yaml
  src/packaging/patchset/threads.yaml
  src/packaging/patchset/uds.yaml
  src/packaging/patchset/vdo.yaml
Labels: private testing done

#143 Delete MegaRaid support, since we don't have MegaRaid cards any more
  src/perl/Permabit/Makefile
  src/perl/Permabit/MegaRaid/Adapter.pm
  src/perl/Permabit/MegaRaid/Makefile
  src/perl/Permabit/MegaRaid/MegaCli.pm
  src/perl/Permabit/MegaRaid/MockMegaRaid/Adapter.pm
  src/perl/Permabit/MegaRaid/MockMegaRaid/FakeUserMachine.pm
  src/perl/Permabit/MegaRaid/MockMegaRaid/Makefile
  src/perl/Permabit/MegaRaid/MockMegaRaid/MegaCli.pm
  src/perl/Permabit/MegaRaid/PhysicalDisk.pm
  src/perl/Permabit/MegaRaid/Utils.pm
  src/perl/Permabit/MegaRaid/VirtualDevice.pm
  src/perl/Permabit/MegaRaid/VirtualDeviceConfig.pm
  src/perl/Permabit/StorageStack.pm
  src/perl/Permabit/UserMachine.pm
  src/perl/Permabit/testcases/MegaRaid_t1.pm
  src/perl/vdotest/VDOTest/VDOFIOPerfTest.pm
Labels: private testing done

#148 Ingest 6.9 kernel changes
  src/c++/devices/common.c
  src/c++/uds/src/uds/io-factory.c
  src/c++/uds/userLinux/tests/getTestIndexNames.c
  src/c++/uds/userLinux/uds/linux/blkdev.h
  src/c++/vdo/base/dm-vdo-target.c
  src/c++/vdo/tests/testDM.c
  src/c++/vdo/tests/vdoTestBase.c
  src/packaging/kpatch/Makefile.upstream
Labels: private testing done

#149 [VDO-5759] Add testing the ability to build from tarballs to the archive target
  src/Makefile
Labels: private testing failed, private testing done

#150 [VDO-5770] Fix tests that use vdoFillIndex
  src/c++/vdo/user/vdoFillIndex.c
Labels: private testing done

#151 [VDO-5735] Remove unused user tools
  src/c++/vdo/user/.gitignore
  src/c++/vdo/user/Makefile
  src/c++/vdo/user/dmeventd_lvm.h
  src/c++/vdo/user/dmeventd_vdo.c
  src/c++/vdo/user/dmeventd_vdo.vers
  src/c++/vdo/user/man/Makefile
  src/c++/vdo/user/man/vdodmeventd.8
  src/c++/vdo/user/man/vdodumpconfig.8
  src/c++/vdo/user/man/vdoregenerategeometry.8
  src/c++/vdo/user/man/vdosetuuid.8
  src/c++/vdo/user/vdoDMEventd.c
  src/c++/vdo/user/vdoDumpConfig.c
  src/c++/vdo/user/vdoFillIndex.c
  src/c++/vdo/user/vdoRegenerateGeometry.c
  src/c++/vdo/user/vdoSetUUID.c
  src/packaging/src-dist/MANIFEST.yaml
  src/packaging/src-dist/user/utils/vdo/Makefile
  src/packaging/src-dist/user/utils/vdo/man/Makefile
  src/packaging/src-dist/vdo.spec
  src/perl/Permabit/BlockDevice/VDO.pm
  src/perl/vdotest/VDOTest.pm
  src/perl/vdotest/VDOTest/DebugTools.pm
  src/perl/vdotest/VDOTest/RegenerateGeometry.pm
  src/perl/vdotest/VDOTest/Suspend.pm
Labels: private testing done

#152 [VDO-5771] Fix non-standard device stacks during vdo stop
  src/perl/Permabit/BlockDevice/VDO.pm
  src/perl/Permabit/BlockDevice/VDO/LVMManaged.pm
Labels: private testing done

#153 Remove Managed VDO block device
  src/perl/Permabit/BlockDevice/VDO/Managed.pm
  src/perl/Permabit/BlockDevice/VDO/Upgrade.pm
  src/perl/vdotest/VDOTest/BlockDevice02.pm
  src/perl/vdotest/VDOTest/BlockDevice03.pm
  src/perl/vdotest/VDOTest/Create03.pm
  src/perl/vdotest/VDOTest/LargeRebuild.pm
  src/perl/vdotest/VDOTest/MemoryFailBase.pm
  src/perl/vdotest/VDOTest/ReadWriteStress.pm
  src/perl/vdotest/VDOTest/RebuildDuration.pm
  src/perl/vdotest/VDOTest/SlabCount01.pm
  src/perl/vdotest/VDOTest/VDOPerfBase.pm
  src/perl/vdotest/VDOTest/Vdorecover.pm
  src/perl/vdotest/VDOTest/Zero01.pm
Labels: public testing running

#154 dm vdo: Disable FEDORA38 testing and replace head with FEDORA39.
  src/perl/Permabit/SupportedScenarios.yaml
  src/perl/Permabit/SupportedVersions.pm
  src/perl/nightly/NightlyBuildType/VDOCheckin.pm
  src/perl/nightly/NightlyRunRules.pm
  src/perl/udstest/Makefile
  src/perl/vdotest/Makefile
  src/perl/vdotest/vdotests.suites
Labels: private testing done

#155 [VDO-5776] Fix FullWarnDmEventd
  src/perl/vdotest/VDOTest/FullBase.pm
  src/perl/vdotest/VDOTest/FullWarnDmEventd.pm
Labels: private testing done

#157 Use swap macro from kernel in swap_open_chapter()
  src/c++/uds/src/uds/index.c
  src/c++/uds/userLinux/uds/asm/unaligned.h
Labels: private testing done

#158 [VDO-5769] dm vdo: Adapt to RHEL 9 kernel backports
  src/c++/uds/kernelLinux/defines
  src/c++/uds/kernelLinux/tests/getTestIndexNames.c
Labels: private testing done
