Repository dm-vdo/vdo-devel, pull requests merged in 2024-01, with the labels that each got.

#56 Add FEDORA39 to test suites
  src/perl/Permabit/SupportedVersions.pm
  src/perl/nightly/NightlyRunRules.pm
  src/perl/udstest/udstests.suites
  src/perl/vdotest/VDOTest.pm
  src/perl/vdotest/vdotests.suites
Labels: private testing done

#58 VDO-5377: update vdorecover test so that it works on a current lab PFARM
  src/perl/vdotest/VDOTest/Vdorecover.pm
  src/perl/vdotest/vdotests.suites
Labels: public testing failed, private testing done

#57 [VDO-5637] Updated vdorecover to work on LVMVDO volumes
  src/tools/vdorecover/vdorecover
Labels: public testing failed, private testing done

#63 [VDO-5637] Fix vdorecover for umounted LVMVDO volumes
  src/tools/vdorecover/vdorecover
Labels: private testing done

#64 [VDO-5377] Fix vdorecover test timing issues in testFullFilesystem
  src/perl/Permabit/FileSystem.pm
  src/perl/vdotest/VDOTest/Vdorecover.pm
Labels: public testing failed, private testing done

#66 Allow fsck exit status 1 (filesystem errors corrected). [VDO-5638]
  src/perl/Permabit/FileSystem.pm
Labels: private testing done

#67 [VDO-5654] Ingest minor block map fixes
  src/c++/vdo/base/block-map.c
  src/c++/vdo/base/block-map.h
Labels: private testing failed

#68 [VDO-5657] Ingest error code patches from upstream
  src/c++/uds/src/uds/errors.c
  src/c++/uds/src/uds/errors.h
  src/c++/uds/src/uds/index-layout.c
  src/c++/uds/src/uds/index-session.c
  src/c++/vdo/base/data-vio.c
  src/c++/vdo/base/dm-vdo-target.c
  src/c++/vdo/base/status-codes.c
  src/c++/vdo/base/status-codes.h
  src/c++/vdo/tests/Load_t1.c
  src/c++/vdo/tests/Resize_t1.c
Labels: private testing done

#70 [VDO-5655] dm vdo data-vio: rename is_trim flag to is_discard
  src/c++/vdo/base/block-map.c
  src/c++/vdo/base/data-vio.c
  src/c++/vdo/base/data-vio.h
  src/c++/vdo/base/types.h
Labels: private testing done

#69 [VDO-5642] Disable Volume_n4 StumblingGet test
  src/c++/uds/src/tests/Volume_n4.c
Labels: private testing done

#71 [VDO-5656] Properly handle kernel-only files from upstream dm-vdo
  src/packaging/kpatch/Kconfig.upstream
  src/packaging/kpatch/Makefile
  src/packaging/kpatch/Makefile.upstream
  src/perl/bin/transformUpstreamPatch.pl
Labels: private testing done

#73 Fix small nits
  src/c++/uds/src/uds/index-layout.c
  src/c++/uds/src/uds/index-page-map.c
  src/c++/uds/src/uds/index-session.c
  src/c++/uds/src/uds/index.c
  src/c++/vdo/base/dedupe.c
  src/c++/vdo/base/slab-depot.c
Labels: private testing failed, private testing done

#74 [VDO-5592] Remove nr_requests check
  src/perl/vdotest/VDOTest/Sysfs.pm
Labels: private testing done

#76 Copy Makefile and Kconfig during prepare step
  src/packaging/kpatch/Makefile
Labels: private testing done

#72 Add support to test dm-linux using vdo-devel perl infra
  src/Makefile
  src/packaging/dmlinux/Makefile
  src/packaging/dmlinux/kernel/Makefile
  src/packaging/dmlinux/kvdo.spec
  src/perl/vdotest/Makefile
  src/perl/vdotest/VDOTest.pm
Labels: private testing done

#77 [VDO-5661] Ingest sparse warning patches from upstream
  src/c++/uds/src/uds/index.c
  src/c++/uds/userLinux/uds/linux/blkdev.h
  src/c++/uds/userLinux/uds/linux/compiler_attributes.h
  src/c++/vdo/base/Makefile.common
  src/c++/vdo/base/block-map.c
  src/c++/vdo/base/constants.c
  src/c++/vdo/base/constants.h
  src/c++/vdo/base/data-vio.c
  src/c++/vdo/base/dedupe.c
  src/c++/vdo/base/encodings.c
  src/c++/vdo/base/encodings.h
  src/c++/vdo/base/io-submitter.c
  src/c++/vdo/base/io-submitter.h
  src/c++/vdo/base/recovery-journal.c
  src/c++/vdo/base/vdo.c
  src/c++/vdo/base/vio.c
  src/c++/vdo/base/vio.h
  src/packaging/kpatch/Makefile.upstream
  src/packaging/patchset/vdo.yaml
  src/packaging/src-dist/MANIFEST.yaml
Labels: private testing done
