Repository dm-vdo/vdo-devel, pull requests merged in 2025-02, with the labels that each got.

#242 ci: allow org members to approve outside submitter PRs
  .github/workflows/ci.yml
Labels: private testing done

#243 [VDO-5837] dm vdo: build VDO programs in tree with -D_FORTIFY_SOURCE=2
  src/c++/defines
Labels: private testing done

#245 Update ci.yml to use usernames directly.
  .github/workflows/ci.yml
Labels: private testing running

#240 [VDO-5886] dm vdo user: increase minimum slab size for users
  src/c++/vdo/user/man/vdoformat.8
  src/c++/vdo/user/vdoFormat.c
Labels: private testing failed, private testing done

#250 [VDO-5886] dm vdo user: increase minimum slab size for users
  src/c++/vdo/user/man/vdoformat.8
  src/c++/vdo/user/vdoFormat.c
Labels: private testing done

#252 Remove unused function and its imports
  src/perl/Permabit/AlbireoTestUtils.pm
Labels: public testing running

#247 Remove a couple of remaining references to rings.
  src/c++/vdo/base/block-map.c
  src/c++/vdo/base/dedupe.c
  src/c++/vdo/base/packer.h
  src/c++/vdo/base/priority-table.c
  src/c++/vdo/base/recovery-journal.h
  src/c++/vdo/base/slab-depot.c
  src/c++/vdo/base/wait-queue.c
Labels: private testing done

#251 dm vdo: minor cleanups and build changes based on W=1 module build
  src/c++/vdo/base/encodings.h
  src/c++/vdo/kernel/Makefile.module.in
Labels: private testing done

#182 [VDO-5749] Add tests for Thin Pools using VDO as data devices.
  src/perl/Permabit/BlockDevice/LVM/Thin.pm
  src/perl/Permabit/BlockDevice/LVM/ThinPool.pm
  src/perl/Permabit/BlockDevice/VDO/LVMVDO.pm
  src/perl/Permabit/BlockDevice/VDO/LVMVDO/Managed.pm
  src/perl/Permabit/BlockDevice/VDO/LVMVDO/ThinPool.pm
  src/perl/Permabit/BlockDevice/VDO/Upgrade.pm
  src/perl/Permabit/StorageStack.pm
  src/perl/Permabit/VolumeGroup.pm
  src/perl/vdotest/VDOTest.pm
  src/perl/vdotest/VDOTest/BlockDevice01.pm
  src/perl/vdotest/VDOTest/DebugTools.pm
  src/perl/vdotest/VDOTest/DiscardThin.pm
  src/perl/vdotest/VDOTest/GrowPhysical01.pm
  src/perl/vdotest/VDOTest/RebuildBase.pm
  src/perl/vdotest/VDOTest/RebuildDuration.pm
  src/perl/vdotest/VDOTest/RebuildStress03.pm
  src/perl/vdotest/VDOTest/ThinVDO.pm
  src/perl/vdotest/VDOTest/Vdorecover.pm
Labels: private testing done

#258 [VDO-5889] Fix device name used in changeVDOSetting
  src/perl/Permabit/BlockDevice/VDO/LVMVDO.pm
Labels: private testing done

#259 [RHEL-59337] dm vdo: add missing spin_lock_init
  src/c++/vdo/base/dedupe.c
Labels: private testing failed, private testing done

#230 [VDO-5868,RHEL-12834] Speed up scanning of loaded slab refcount blocks
  src/c++/vdo/base/slab-depot.c
  src/c++/vdo/base/slab-depot.h
  src/c++/vdo/tests/RefCounts_t3.c
  src/c++/vdo/tests/RefCounts_x1.c
Labels: private testing done

#264 [VDO-5888] dm vdo test: update expected instance number for test changes
  src/perl/vdotest/VDOTest/Sysfs.pm
Labels: private testing done

#244 dm vdo indexer: reorder uds_request to reduce padding
  src/c++/uds/src/uds/index-session.c
  src/c++/uds/src/uds/indexer.h
  src/c++/uds/userLinux/uds/linux/stddef.h
  src/packaging/src-dist/MANIFEST.yaml
Labels: public testing running

#268 [VDO-5890] Fix issue with auto activation
  src/perl/Permabit/BlockDevice/VDO.pm
Labels: private testing done
